Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.ShoppingCart:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        shop:
          position: 'end'
          label: NeosRulez.ShoppingCart:Main:shop
    fusion:
      autoInclude:
        NeosRulez.ShoppingCart: true
    modules:
      shoppingcart:
        label: NeosRulez.ShoppingCart:Main:shop
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'Shop Admin'
        icon: 'icon-shopping-cart'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          country:
            label: 'Länder'
            controller: '\NeosRulez\ShoppingCart\Controller\CountryController'
            description: NeosRulez.ShoppingCart:Main:countrymodulelabel
            icon: 'icon-globe'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:countrymoduleactionlabel
                title: NeosRulez.ShoppingCart:Main:countrymoduleactionlabel
          delivery:
            label: 'Versandarten'
            controller: '\NeosRulez\ShoppingCart\Controller\DeliveryController'
            description: NeosRulez.ShoppingCart:Main:deliverymodulelabel
            icon: 'icon-plane'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:deliverymoduleactionlabel
                title: NeosRulez.ShoppingCart:Main:deliverymoduleactionlabel
          costdelivery:
            label: NeosRulez.ShoppingCart:Main:deliverycosts
            controller: '\NeosRulez\ShoppingCart\Controller\DeliverycostController'
            description: NeosRulez.ShoppingCart:Main:deliverycostsmoddescription
            icon: 'icon-truck'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:newdeliverycosts
                title: NeosRulez.ShoppingCart:Main:newdeliverycosts
          coupon:
            label: NeosRulez.ShoppingCart:Main:coupon
            controller: '\NeosRulez\ShoppingCart\Controller\CouponController'
            description: NeosRulez.ShoppingCart:Main:couponmoddescription
            icon: 'icon-ticket-alt'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:coupon
                title: NeosRulez.ShoppingCart:Main:coupon
          option:
            label: NeosRulez.ShoppingCart:Main:option
            controller: '\NeosRulez\ShoppingCart\Controller\OptionController'
            description: NeosRulez.ShoppingCart:Main:optionmoddescription
            icon: 'icon-list'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:option
                title: NeosRulez.ShoppingCart:Main:option
NeosRulez:
  ShoppingCart:
    taxinclusive: false
    linkToCart: '/de/warenkorb.html'
    linkToHome: '/'
    standardDelivery: 'f7fe9c29-e24b-4840-a4ac-092fbef0db49'
    standardCountry: 'c7fbefb3-120d-4997-b9d4-433f33b3313d'
    senderEmailAddress: 'postmaster@patriceckhart.com'
    orderEmailAddress: 'mail@patriceckhart.com'
    confirmationSubject: 'Bestellbestätigung'
    orderSubject: 'Bestellung'
    mailLogo: 'http://dev.localhost/_Resources/Persistent/da2b254877a5c7bb4155ee4f112495899ac075ef/Testlogo.png'
    mailAdditional: 'Additional Information'
    payPal: false
    payPalReturnUri: '/paymentsuccessful.html'
    payPalHostedButtonId: 'LTRDGNR38ZH6A'
    payPalBusiness: 'mail@patriceckhart.com'
    coupons: true
    mailBodyTemplate: 'resource://NeosRulez.ShoppingCart/Private/Templates/Mail/Template.html'
    mailArticleTemplate: 'resource://NeosRulez.ShoppingCart/Private/Partials/Mail/Article.html'