Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.ShoppingCart:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        shop:
          position: 'end'
          label: NeosRulez.ShoppingCart:Main:shop
    fusion:
      autoInclude:
        NeosRulez.ShoppingCart: true
    modules:
      shoppingcart:
        label: NeosRulez.ShoppingCart:Main:shop
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'Shop Admin'
        icon: 'icon-shopping-cart'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          country:
            label: 'Länder'
            controller: '\NeosRulez\ShoppingCart\Controller\CountryController'
            description: NeosRulez.ShoppingCart:Main:countrymodulelabel
            icon: 'icon-globe'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:countrymoduleactionlabel
                title: NeosRulez.ShoppingCart:Main:countrymoduleactionlabel
          delivery:
            label: 'Versandarten'
            controller: '\NeosRulez\ShoppingCart\Controller\DeliveryController'
            description: NeosRulez.ShoppingCart:Main:deliverymodulelabel
            icon: 'icon-plane'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:deliverymoduleactionlabel
                title: NeosRulez.ShoppingCart:Main:deliverymoduleactionlabel
          deliverycost:
            label: NeosRulez.ShoppingCart:Main:deliverycosts
            controller: '\NeosRulez\ShoppingCart\Controller\DeliverycostController'
            description: NeosRulez.ShoppingCart:Main:deliverycostsmoddescription
            icon: 'icon-truck'
            actions:
              index:
                label: NeosRulez.ShoppingCart:Main:newdeliverycosts
                title: NeosRulez.ShoppingCart:Main:newdeliverycosts
NeosRulez:
  ShoppingCart:
    taxinclusive: false
    linkToCart: '/de/warenkorb.html'
    linkToHome: '/'
    standardDelivery: '7ac6ba34-5992-4b9f-8d21-bdc5966c945e'
    standardCountry: '222a091c-d95e-4487-b15e-194c1b9c9741'
    senderEmailAddress: 'postmaster@patriceckhart.com'
    orderEmailAddress: 'mail@patriceckhart.com'
    confirmationSubject: 'Bestellbestätigung'
    orderSubject: 'Bestellung'
    mailLogo: 'http://dev.localhost/_Resources/Persistent/da2b254877a5c7bb4155ee4f112495899ac075ef/Testlogo.png'
    payPal: false
    payPalReturnUri: '/paymentsuccessful.html'
    payPalHostedButtonId: 'LTRDGNR38ZH6A'
    payPalBusiness: 'mail@patriceckhart.com'